export const publishersList = [
  { id: 1, name: "Азбука" },
  { id: 2, name: "АСТ" },
  { id: 3, name: "БОМБОРА" },
  { id: 4, name: "Вече" },
  { id: 5, name: "Дрофа" },
  { id: 6, name: "Росмэн" },
  { id: 7, name: "Махаон" },
  { id: 8, name: "МИФ" },
  { id: 9, name: "Inspiria" },
  { id: 10, name: "Like Book" },
  { id: 11, name: "Питер" },
  { id: 12, name: "Popcorn Books" },
  { id: 13, name: "Просвещение" },
  { id: 14, name: "РИПОЛ-классик" },
  { id: 15, name: "Soda Press" },
  { id: 16, name: "Центрполиграф" },
  { id: 17, name: "Черным-бело" },
  { id: 18, name: "Эксмо" },
  { id: 19, name: "Комильфо" },
  { id: 20, name: "Freedom" },
];
